# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Name', models.CharField(max_length=250)),
                ('Poster_Link', models.CharField(max_length=1250)),
                ('Poster_type', models.CharField(max_length=250)),
                ('Poster_creator', models.CharField(max_length=250)),
            ],
        ),
    ]
